sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t octaviusjr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true octaviusjr/react-test npm run test -- --coverage

after_success:
  - docker build -t octaviusjr/multi-client ./client
  - docker build -t octaviusjr/multi-nginx ./nginx
  - docker build -t octaivusjr/multi-server ./server
  - docker build -t octaviusjr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push octaviusjr/multi-client
  - docker push octaviusjr/multi-nginx
  - docker push octaivusjr/multi-server
  - docker push octaviusjr/multi-worker
  


